# Generated by Django 4.1.3 on 2022-11-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markirovka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tara',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тара'),
        ),
    ]
