# Generated by Django 4.1.3 on 2022-11-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markirovka', '0003_alter_country_name_alter_donwload_codes_aggr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donwload_codes',
            options={'verbose_name': 'Потребительский код', 'verbose_name_plural': 'Потребительские коды'},
        ),
        migrations.AlterModelOptions(
            name='donwload_codes_korob',
            options={'verbose_name': 'Групповой код', 'verbose_name_plural': 'Групповое коды'},
        ),
        migrations.AlterField(
            model_name='korob',
            name='korob_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markirovka.donwload_codes_korob', verbose_name='Групповой код'),
        ),
    ]
