# Generated by Django 4.1.3 on 2022-12-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markirovka', '0006_alter_country_options_alter_product_tara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_codes_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='download-codes/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='donwload_codes',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Групповой код'),
        ),
    ]
